name: Build

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.release_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        if: ${{ inputs.free-disk-space == true }}
        with:
          tool-cache: true

      - name: Build container image
        uses: getdevopspro/github-actions/buildx-bake@v0.3.22
        with:
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          bake-targets: build
