name: Build Variants

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

jobs:
  files-variants:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        jetson_version_pair: ["36.4.3,jammy", "35.6.1,focal"]
        jetson_samplefs_flavor: ["minimal", "basic", "desktop"]
    name: Build for ${{ matrix.variant }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Build rootfs variants files
        run: |
          make build-rootfs-variant \
            JETSON_VERSION_PAIR=${{ matrix.jetson_version_pair }} \
            JETSON_SAMPLEFS_FLAVOR=${{ matrix.jetson_samplefs_flavor }}

      - name: Upload shared artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/.shared
          include-hidden-files: true
          name: shared-${{ matrix.jetson_version_pair }}-${{ matrix.jetson_samplefs_flavor }}

  build-variants:
    runs-on: ubuntu-24.04-arm
    needs: files-variants
    outputs:
      version: ${{ steps.release_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/.shared
          pattern: shared-*
          merge-multiple: true

      - name: Build container image
        uses: getdevopspro/github-actions/buildx-bake@v0.2.12
        with:
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          bake-targets: build-variants
