name: Release

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: read
  statuses: read

jobs:
  release:
    name: Job
    uses: getdevopspro/github-actions/.github/workflows/release.yml@v8.3.12
    with:
      version-makefile: Makefile
      git-add-files: Makefile
      git-user-name: getdevopspro-cibot
      git-user-email: 203600057+getdevopspro-cibot@users.noreply.github.com
      changelog-enabled: true
      update-release-enabled: true
