name: Release

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  promote:
    uses: getdevopspro/github-actions/.github/workflows/promote.yml@v0.2.12
    with:
      git-user-name: cleanlogix-cibot
      git-user-email: 203600057+getdevopspro-cibot@users.noreply.github.com
